### ISSUE TITLE
Error of Mixed Content (HTTP vs HTTPS) in fetch "http://www.omdbapi.com" 

### ISSUE THREAD

**Issue by protron** [fernandeznico/argenteamIMDbScore#1]
I was not seeing any change in the Argenteam page and I found that the extensions was throwing an error when fetching `http://www.omdbapi.com`. It's failing due to HTTP vs HTTPS with the following message:

    Mixed Content: The page at 'https://argenteam.net/' was loaded over HTTPS, but requested an insecure resource 'http://www.omdbapi.com/?apikey=6d863fde&t=Justice%20Society:%20World%20War%20II&y=2021'. This request has been blocked; the content must be served over HTTPS.

Screenshot of the problem:
![image](https://user-images.githubusercontent.com/465963/117557771-e6bbc300-b04c-11eb-8dee-64aa306a8cea.png)

The problem seems to be resolved by simply changing line 14 from `http://` into `https://`. I'll a create a PR with that change now.

**Comment by protron** [comment]
I created that PR #2 with the fix.

By the way, great extension!
With actually few lines of easy to understand code you managed to make the main page of argenteam actually a lot better.
Thank you!!!

**Comment by fernandeznico** [comment]
Thank you so much!!
